staging-settings:
  user-workflow:
    workflow-name: "optimus-bnpl-late-fee-staging"
  workflow-artifacts:
    workflow-path: "./main.go"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

production-settings:
  user-workflow:
    workflow-name: "optimus-bnpl-late-fee-production"
  workflow-artifacts:
    workflow-path: "./main.go"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
